server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
     
          uri: lb://user-service
          predicates:
            
            - Path=/users/**, /auth/**
        - id: inscription-service
          
          uri: lb://inscription-service
          predicates:
            - Path=/inscriptions/**
