server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:4200"
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**, /auth/**

        - id: inscription-service
          uri: lb://inscription-service
          predicates:
            - Path=/inscriptions/**, /campagnes/**, /documents/**

        - id: soutenance-service
          uri: lb://soutenance-service
          predicates:
            - Path=/soutenances/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**, /api/test/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
