server:
  port: 8084

spring:
  application:
    name: soutenance-service
  
  # Configuration Base de Données
  datasource:
    url: jdbc:postgresql://localhost:5432/soutenance_db
    username: postgres
    password: omar123
    driver-class-name: org.postgresql.Driver
  
  # Configuration JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Configuration Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# Actuator pour le monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
